import type { Metadata } from "next";
import { El_Messiri, Geist, Geist_Mono, Karla } from "next/font/google";
import "./globals.css";

// ------------------------------------------------------------
// 1. Define Fonts
// ------------------------------------------------------------

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const elMessiri = El_Messiri({
  variable: "--font-el-messiri",
  subsets: ["latin"],
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

// ------------------------------------------------------------
// 2. Metadata
// ------------------------------------------------------------

export const metadata: Metadata = {
  title: "Touvel",
  description: "Generated by create next app",
};

// ------------------------------------------------------------
// 3. Root Layout
// ------------------------------------------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${elMessiri.variable} ${karla.className} h-full antialiased bg-white text-[#171717]`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
